/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTwinsRouteImport } from './routes/dashboard/twins'
import { Route as DashboardStudioRouteImport } from './routes/dashboard/studio'
import { Route as DashboardScriptsRouteImport } from './routes/dashboard/scripts'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTwinsRoute = DashboardTwinsRouteImport.update({
  id: '/twins',
  path: '/twins',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudioRoute = DashboardStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScriptsRoute = DashboardScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/scripts': typeof DashboardScriptsRoute
  '/dashboard/studio': typeof DashboardStudioRoute
  '/dashboard/twins': typeof DashboardTwinsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/scripts': typeof DashboardScriptsRoute
  '/dashboard/studio': typeof DashboardStudioRoute
  '/dashboard/twins': typeof DashboardTwinsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/scripts': typeof DashboardScriptsRoute
  '/dashboard/studio': typeof DashboardStudioRoute
  '/dashboard/twins': typeof DashboardTwinsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/scripts'
    | '/dashboard/studio'
    | '/dashboard/twins'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/scripts'
    | '/dashboard/studio'
    | '/dashboard/twins'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/scripts'
    | '/dashboard/studio'
    | '/dashboard/twins'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/twins': {
      id: '/dashboard/twins'
      path: '/twins'
      fullPath: '/dashboard/twins'
      preLoaderRoute: typeof DashboardTwinsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/studio': {
      id: '/dashboard/studio'
      path: '/studio'
      fullPath: '/dashboard/studio'
      preLoaderRoute: typeof DashboardStudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scripts': {
      id: '/dashboard/scripts'
      path: '/scripts'
      fullPath: '/dashboard/scripts'
      preLoaderRoute: typeof DashboardScriptsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardScriptsRoute: typeof DashboardScriptsRoute
  DashboardStudioRoute: typeof DashboardStudioRoute
  DashboardTwinsRoute: typeof DashboardTwinsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardScriptsRoute: DashboardScriptsRoute,
  DashboardStudioRoute: DashboardStudioRoute,
  DashboardTwinsRoute: DashboardTwinsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
